sudo: false
language: node_js

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "6"
    - os: linux
      node_js: "4.3"
    - os: osx
      node_js: "7"
  allow_failures:
    - os: osx
  fast_finish: true

script: npm run travis

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage
